### PR TITLE
GWTRAR-35: IE9 only white page: remove doctype specification html 4

### PR DESCRIPTION
**Pull request by janvenstermans**
example at http://dev.geomajas.org/geomajas-gwt-quickstart-application_GWTRAR-35_IE9whitePage/

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by streulma** [comment]
Matthias Streulens: +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by jandm** [comment]
+1: binding

**Comment by janvenstermans** [comment]
Vote count:
Oliver May: +1 (binding)
Jan De Moerloose: +1: binding

Jan Venstermans: +1
Matthias Streulens: +1

Bug fix vote successful

**Pull request merged**
