### PR TITLE
GWTRAR-32: copied documentation from documentation project to readme.md

### PR DESCRIPTION
**Pull request by janvenstermans**
See readm.md in https://github.com/geomajas/geomajas-gwt-quickstart-application/tree/JV_GWTRAR-32_copyDocumentationToReadmeMd

compare with http://files.geomajas.org/enduser-application-smartgwt/doc/master.html

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
+1 (binding)

**Comment by jandm** [comment]
+1 (binding)

**Comment by janvenstermans** [comment]
Vote count: 
Oliver May: +1 (binding)
Jan De Moerloose: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
